### PR TITLE
fix: improve pushing for goreleaser/render-version-schema

### LINKED ISSUE #33: Fix push issues for goreleaser/render-version-schema
https://app.circleci.com/pipelines/github/ory/hydra/1385/workflows/598d3fd0-a4e1-472d-b2ec-6e50c92b6185/jobs/24576

### PR DESCRIPTION
**Pull request by zepatrik**
Closes #33

### CODE REVIEW

File: src/scripts/releaser/render-version-schema.sh [hunk 1]
```diff
@@ -5,7 +5,10 @@ set -Eeuox pipefail
 bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/install/git.sh)
 bash <(curl https://raw.githubusercontent.com/ory/cli/master/install.sh) -b $GOPATH/bin
 
+git fetch origin
+git checkout -b master origin/master
+
 ory dev schema render-version $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG
+
 git commit -a -m "autogen: add $CIRCLE_TAG to version.schema.json"
```
Comment (aeneasr) [inline src/scripts/releaser/render-version-schema.sh]:
```suggestion
ory dev schema render-version $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG

branch="$(date +%s)"
git fetch origin
git stash
git checkout -b "$branch"
git stash pop
git commit -a -m "autogen: add $CIRCLE_TAG to version.schema.json"
git pull origin master --rebase
git push origin HEAD:master
```

File: src/scripts/releaser/render-version-schema.sh [hunk 2]
```diff
@@ -5,7 +5,10 @@ set -Eeuox pipefail
...
-# pushing detached HEAD to master
-git push origin HEAD:master
+git push origin master
```
Comment (aeneasr) [inline src/scripts/releaser/render-version-schema.sh]:
```suggestion
```

**Review by aeneasr — CHANGES_REQUESTED** [review]
